/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import entities.Service;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JLabel;

/**
 *
 * @author trinh
 */
public class ServiceComponent extends javax.swing.JPanel {

    private final Service service;

    /**
     * Creates new form ServiceComponent
     */
    public ServiceComponent(Service service) {
        this.service = service;
        initComponents();

        setupService(service);
    }

    public Service getService() {
        return service;
    }

    public JLabel getLbRemove() {
        return lbRemove;
    }

    private void setupService(Service service) {
        int amount = service.getAmount();
        Double price = service.getPrice();
        String sname = service.getName();
        String name = sname.substring(0, 1).toUpperCase() + sname.substring(1);
        NumberFormat formatter = NumberFormat.getInstance(new Locale("en", "US"));
        String sprice = formatter.format(price);
        if (amount == 0) {
            lbServiceStatus.setkForeGround(Color.WHITE);
            lbServiceStatus.setkStartColor(Color.RED);
            lbServiceStatus.setkEndColor(Color.RED);
            lbServiceStatus.setkHoverStartColor(Color.RED);
            lbServiceStatus.setkHoverEndColor(Color.RED);
            lbServiceStatus.setkHoverForeGround(Color.WHITE);
            lbServiceStatus.setkPressedColor(Color.RED);
            lbServiceStatus.setText("Hết hàng");
        } else {
            lbServiceStatus.setkForeGround(new Color(102, 102, 102));
            lbServiceStatus.setkStartColor(Color.WHITE);
            lbServiceStatus.setkEndColor(Color.WHITE);
            lbServiceStatus.setkHoverStartColor(Color.WHITE);
            lbServiceStatus.setkHoverEndColor(Color.WHITE);
            lbServiceStatus.setkHoverForeGround(new Color(102, 102, 102));
            lbServiceStatus.setkPressedColor(Color.WHITE);
            lbServiceStatus.setText("Còn " + amount);
        }
        lbServiceName.setText(name);
        lbServicePrice.setText(sprice + " VNĐ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbRemove = new javax.swing.JLabel();
        lbServiceStatus = new keeptoo.KButton();
        lbImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbServiceName = new javax.swing.JLabel();
        lbServicePrice = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(95, 120));
        setMinimumSize(new java.awt.Dimension(95, 120));
        setPreferredSize(new java.awt.Dimension(95, 120));

        jPanel1.setMinimumSize(new java.awt.Dimension(91, 116));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(91, 74));
        jPanel2.setLayout(null);

        lbRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/items/closered20.png"))); // NOI18N
        jPanel2.add(lbRemove);
        lbRemove.setBounds(71, 0, 20, 20);

        lbServiceStatus.setBorder(null);
        lbServiceStatus.setText("Còn 5");
        lbServiceStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbServiceStatus.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        lbServiceStatus.setkBorderRadius(16);
        lbServiceStatus.setkEndColor(new java.awt.Color(255, 0, 0));
        lbServiceStatus.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        lbServiceStatus.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        lbServiceStatus.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        lbServiceStatus.setkPressedColor(new java.awt.Color(255, 0, 0));
        lbServiceStatus.setkSelectedColor(new java.awt.Color(255, 255, 255));
        lbServiceStatus.setkStartColor(new java.awt.Color(255, 0, 0));
        lbServiceStatus.setMaximumSize(new java.awt.Dimension(55, 15));
        lbServiceStatus.setMinimumSize(new java.awt.Dimension(55, 15));
        lbServiceStatus.setPreferredSize(new java.awt.Dimension(55, 15));
        jPanel2.add(lbServiceStatus);
        lbServiceStatus.setBounds(2, 3, 55, 15);

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/service.png"))); // NOI18N
        jPanel2.add(lbImage);
        lbImage.setBounds(0, 0, 91, 74);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(91, 42));

        lbServiceName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbServiceName.setForeground(new java.awt.Color(102, 102, 102));
        lbServiceName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbServiceName.setMaximumSize(new java.awt.Dimension(83, 25));
        lbServiceName.setMinimumSize(new java.awt.Dimension(83, 25));
        lbServiceName.setPreferredSize(new java.awt.Dimension(83, 25));

        lbServicePrice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbServicePrice.setForeground(new java.awt.Color(102, 102, 102));
        lbServicePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbServiceName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbServicePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbServicePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbRemove;
    private javax.swing.JLabel lbServiceName;
    private javax.swing.JLabel lbServicePrice;
    private keeptoo.KButton lbServiceStatus;
    // End of variables declaration//GEN-END:variables

}
